language: csharp
solution: src/logzio-dotnet.sln
mono: none
dotnet: 2.0.0
cache:
  directories:
    - $TRAVIS_BUILD_DIR/src/packages
    - $TRAVIS_BUILD_DIR/src/testrunner
install:
  - cd src
  - dotnet restore logzio-dotnet.sln
script:
  - dotnet build logzio-dotnet.sln /p:Configuration=Release
  - dotnet test ./UnitTests/UnitTests.csproj
  - dotnet test ./IntegrationTests/IntegrationTests.csproj
notifications:
  slack: logzio:bLRWDmRpTJI4vTdAEDSpZ9Sp
